# Generated by Django 6.0.6 on 2026-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='new', max_length=20),
        ),
    ]
